"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import SiteStyles from "@/components/SiteStyles";
type Lang = "en" | "es";
const content = {
  en: {
    nav: { logo: "SLTapCard", how: "How It Works", features: "Features", pricing: "Pricing", example: "Live Example", dashboard: "Dashboard", cta: "Get Your Card" },
    hero: { badge: "SMART TAP CARDS FOR BUSINESS", title: "Lucio powers your business", subtitle: "Turn every tap into a customer with a smart tap card built for calls, texts, contact saving, lead capture, and instant response.", primary: "Get Your Card", secondary: "View Live Example", tertiary: "See Dashboard", support: "No app required. Works on modern phones. Built for real businesses that want faster response and better conversion." },
    trust: ["Works on Any Phone", "Call + Text + Save Contact", "Lead Capture Ready", "AI + SMS Ready"],
    how: { title: "How it works", steps: [{ title: "Tap or Scan", text: "Your customer taps the card or scans the QR code." }, { title: "Open Your Smart Page", text: "They land on your branded mobile page instantly." }, { title: "Take Action", text: "They can call, text, save your contact, shop, or submit a lead." }, { title: "You Convert Faster", text: "Twilio alerts, contact save, and Lucio AI help you move faster." }] },
    features: { title: "What makes SLTapCard different", items: [{ title: "Smart Tap Experience", text: "NFC + QR on a premium card that opens your business page instantly." }, { title: "Conversion Buttons", text: "Call Now, Text Now, Save Contact, and Shop Now in one place." }, { title: "Lead Capture", text: "Built-in forms can send inquiries directly into your system." }, { title: "VCF Contact Save", text: "Customers can save your contact to their phone in seconds." }, { title: "Twilio SMS Ready", text: "Instant owner alerts and customer confirmation messages." }, { title: "Lucio AI Ready", text: "A smart assistant layer for sales, questions, and lead guidance." }] },
    example: { title: "Real working example", text: "This is not a mock demo page. This is the exact live-use structure tied to JR Tools.", cta: "Open JR Tools Example" },
    pricing: { title: "Simple pricing", plans: [{ name: "Starter", price: "$99", items: ["Custom tap card page", "Call + text buttons", "QR + NFC-ready flow", "Basic branding setup"] }, { name: "Pro", price: "$149", items: ["Everything in Starter", "Lead form", "Save Contact (VCF)", "Shop button / product link"] }, { name: "Elite", price: "$299", items: ["Everything in Pro", "Lucio AI integration", "Dashboard access", "SMS automation setup"] }] },
    final: { title: "Turn every tap into a customer", text: "SLTapCard combines physical cards, mobile conversion pages, contact saving, SMS workflows, and AI into one modern business system.", primary: "Get Started", secondary: "View JR Tools" },
    footer: { line: "Smart Tap Cards for Business", example: "Live Example", dashboard: "Dashboard" }
  },
  es: {
    nav: { logo: "SLTapCard", how: "Cómo Funciona", features: "Funciones", pricing: "Precios", example: "Ejemplo Real", dashboard: "Panel", cta: "Obtén Tu Tarjeta" },
    hero: { badge: "TARJETAS INTELIGENTES PARA NEGOCIOS", title: "Lucio impulsa tu negocio", subtitle: "Convierte cada toque en un cliente con una tarjeta inteligente creada para llamadas, textos, guardar contacto, capturar leads y responder al instante.", primary: "Obtén Tu Tarjeta", secondary: "Ver Ejemplo Real", tertiary: "Ver Panel", support: "No requiere app. Funciona en teléfonos modernos. Creado para negocios reales que quieren responder más rápido y convertir mejor." },
    trust: ["Funciona en Cualquier Teléfono", "Llamar + Texto + Guardar Contacto", "Captura de Leads", "Listo para AI + SMS"],
    how: { title: "Cómo funciona", steps: [{ title: "Toca o Escanea", text: "Tu cliente toca la tarjeta o escanea el código QR." }, { title: "Abre Tu Página Inteligente", text: "Llega al instante a tu página móvil con tu marca." }, { title: "Toma Acción", text: "Puede llamar, mandar texto, guardar tu contacto, comprar o enviar un lead." }, { title: "Conviertes Más Rápido", text: "Las alertas por Twilio, el guardado de contacto y Lucio AI te ayudan a moverte más rápido." }] },
    features: { title: "Qué hace diferente a SLTapCard", items: [{ title: "Experiencia Inteligente", text: "NFC + QR en una tarjeta premium que abre tu página de negocio al instante." }, { title: "Botones de Conversión", text: "Llamar, texto, guardar contacto y comprar en un mismo lugar." }, { title: "Captura de Leads", text: "Formularios integrados que mandan consultas directo a tu sistema." }, { title: "Guardar Contacto (VCF)", text: "Tus clientes guardan tu contacto en segundos." }, { title: "Listo para Twilio", text: "Alertas instantáneas para ti y mensajes de confirmación al cliente." }, { title: "Listo para Lucio AI", text: "Una capa inteligente para ventas, preguntas y guía de leads." }] },
    example: { title: "Ejemplo real funcionando", text: "Esto no es una demo falsa. Es la estructura real en uso conectada a JR Tools.", cta: "Abrir Ejemplo JR Tools" },
    pricing: { title: "Precios simples", plans: [{ name: "Starter", price: "$99", items: ["Página personalizada", "Botones de llamar y texto", "Flujo QR + NFC", "Configuración básica de marca"] }, { name: "Pro", price: "$149", items: ["Todo lo de Starter", "Formulario de leads", "Guardar Contacto (VCF)", "Botón de compra / tienda"] }, { name: "Elite", price: "$299", items: ["Todo lo de Pro", "Integración con Lucio AI", "Acceso a panel", "Automatización SMS"] }] },
    final: { title: "Convierte cada toque en un cliente", text: "SLTapCard combina tarjetas físicas, páginas móviles de conversión, guardado de contacto, flujos SMS e inteligencia artificial en un solo sistema moderno para negocios.", primary: "Empezar", secondary: "Ver JR Tools" },
    footer: { line: "Tarjetas Inteligentes para Negocios", example: "Ejemplo Real", dashboard: "Panel" }
  }
};
function SectionTitle({ eyebrow, title, description }: { eyebrow?: string; title: string; description?: string }) {
  return <div>{eyebrow ? <p className="eyebrow">{eyebrow}</p> : null}<h2 className="sectionTitle">{title}</h2>{description ? <p className="sectionText">{description}</p> : null}</div>;
}
export default function HomePage() {
  const [lang, setLang] = useState<Lang>("en");
  const t = useMemo(() => content[lang], [lang]);
  return (
    <main className="page"><SiteStyles />
      <div className="nav"><div className="container navInner">
        <div className="brand"><div className="brandMark">⚔️</div><div><div className="brandTitle">{t.nav.logo}</div><div className="brandSub">Lucio AI Powered</div></div></div>
        <div className="navLinks"><a href="#how">{t.nav.how}</a><a href="#features">{t.nav.features}</a><a href="#pricing">{t.nav.pricing}</a><Link href="/jrtools">{t.nav.example}</Link><Link href="/dashboard">{t.nav.dashboard}</Link></div>
        <div style={{ display:"flex", alignItems:"center", gap:12 }}><div className="lang"><button className={lang==="en" ? "active" : ""} onClick={() => setLang("en")}>EN</button><button className={lang==="es" ? "active" : ""} onClick={() => setLang("es")}>ES</button></div><Link href="/jrtools" className="primaryBtn">{t.nav.cta}</Link></div>
      </div></div>
      <section className="hero"><div className="heroBg" /><div className="container heroGrid">
        <div><div className="badge">{t.hero.badge}</div><h1 className="heroTitle">{t.hero.title}</h1><p className="heroText">{t.hero.subtitle}</p><div className="heroButtons"><Link href="/jrtools" className="primaryBtn">{t.hero.primary}</Link><Link href="/jrtools" className="secondaryBtn">{t.hero.secondary}</Link><Link href="/dashboard" className="accentBtn">{t.hero.tertiary}</Link></div><p className="support">{t.hero.support}</p></div>
        <div className="heroExample"><div className="panel"><div style={{ display:"flex", justifyContent:"space-between", gap:16, alignItems:"flex-start" }}><div><p className="eyebrow" style={{ marginBottom:6 }}>Live Card Example</p><h3 className="panelTitle">JR Tools</h3></div><div className="pill">card.jrtoolsusa.com/jrtools</div></div><div className="grid2" style={{ marginTop:18 }}><div className="darkCard"><p className="miniLabel">Actions</p><ul className="list"><li>Call Now</li><li>Text Now</li><li>Save Contact</li><li>Shop Now</li></ul></div><div className="darkCard"><p className="miniLabel">System</p><ul className="list"><li>Twilio-ready</li><li>Groq-ready</li><li>Dashboard-ready</li><li>NFC + QR flow</li></ul></div></div><div className="centerNotice">This is a focused product build — one strong example, one clear funnel, one clean brand.</div></div></div>
      </div></section>
      <section className="trustBar"><div className="container trustGrid">{t.trust.map((item) => <div key={item} className="trustItem">{item}</div>)}</div></section>
      <section id="how" className="section"><div className="container"><SectionTitle eyebrow="SYSTEM FLOW" title={t.how.title} description={lang==="en" ? "A simple product flow that turns a physical card into a digital conversion engine." : "Un flujo simple que convierte una tarjeta física en un motor digital de conversión."} /><div className="grid4" style={{ marginTop:38 }}>{t.how.steps.map((step, i) => <div className="card" key={step.title}><div className="brandMark" style={{ width:48, height:48 }}>{i+1}</div><h3>{step.title}</h3><p>{step.text}</p></div>)}</div></div></section>
      <section id="features" className="section altSection"><div className="container"><SectionTitle eyebrow="CORE FEATURES" title={t.features.title} description={lang==="en" ? "Everything you need to position SLTapCard as a finished product, not a gimmick." : "Todo lo que necesitas para posicionar SLTapCard como un producto terminado, no como una curiosidad."} /><div className="grid3" style={{ marginTop:38 }}>{t.features.items.map((item) => <div className="darkCard" key={item.title}><h3 style={{ margin:0, fontSize:24 }}>{item.title}</h3><p>{item.text}</p></div>)}</div></div></section>
      <section className="section"><div className="container"><div className="grid2 ctaBox"><div><SectionTitle eyebrow="LIVE EXAMPLE" title={t.example.title} description={t.example.text} /><div className="heroButtons"><Link href="/jrtools" className="primaryBtn">{t.example.cta}</Link><Link href="/dashboard" className="secondaryBtn">{t.nav.dashboard}</Link></div></div><div className="darkCard"><p className="eyebrow" style={{ marginBottom:6 }}>Included in the flow</p><div className="grid2">{["NFC + QR entry","Call / Text actions","VCF contact save","Lead form capture","Twilio hooks","Groq assistant layer"].map((item) => <div key={item} className="trustItem">{item}</div>)}</div></div></div></div></section>
      <section id="pricing" className="section" style={{ background:"#000" }}><div className="container"><SectionTitle eyebrow="PRICING" title={t.pricing.title} description={lang==="en" ? "Simple enough to sell fast. Strong enough to upsell later." : "Suficientemente simple para vender rápido y suficientemente fuerte para escalar después."} /><div className="grid3" style={{ marginTop:38 }}>{t.pricing.plans.map((plan, idx) => <div className="card" style={{ background: idx===1 ? "rgba(220,38,38,.10)" : "rgba(255,255,255,.03)", borderColor: idx===1 ? "rgba(239,68,68,.6)" : "rgba(255,255,255,.1)" }} key={plan.name}><div className="topRow"><div><h3 style={{ margin:0 }}>{plan.name}</h3><div className="planPrice">{plan.price}</div></div>{idx===1 ? <div className="popular">Popular</div> : null}</div><ul className="list" style={{ marginTop:18 }}>{plan.items.map((item) => <li key={item}>{item}</li>)}</ul><Link href="/jrtools" className={idx===1 ? "primaryBtn" : "secondaryBtn"} style={{ width:"100%", marginTop:18 }}>{t.nav.cta}</Link></div>)}</div></div></section>
      <section className="section"><div className="container"><div className="ctaBox"><SectionTitle eyebrow="FINAL CTA" title={t.final.title} description={t.final.text} /><div className="heroButtons"><Link href="/jrtools" className="primaryBtn">{t.final.primary}</Link><Link href="/jrtools" className="secondaryBtn">{t.final.secondary}</Link></div></div></div></section>
      <footer className="footer"><div className="container footerInner"><div><div className="brandTitle">SLTapCard</div><div className="brandSub" style={{ marginTop:8 }}>{t.footer.line}</div></div><div className="footerLinks"><Link href="/jrtools">{t.footer.example}</Link><Link href="/dashboard">{t.footer.dashboard}</Link><a href="#pricing">{t.nav.pricing}</a></div></div></footer>
    </main>
  );
}
